export const CHECK_SCANNED_REQUEST = "CHECK_SCANNED_REQUEST";
export const CHECK_SCANNED_SUCCESS = "CHECK_SCANNED_SUCCESS";
export const CHECK_SCANNED_FAILURED = "CHECK_SCANNED_FAILURED";
export const CHANGE_IS_SCANNED = "CHANGE_IS_SCANNED";