export const CHECK_ASSET_EXISTS = "CHECK_ASSET_EXISTS";
export const CHECK_ASSET_EXISTS_SUCCESS = "CHECK_ASSET_EXISTS_SUCCESS";
export const CHECK_ASSET_EXISTS_FAILURED = "CHECK_ASSET_EXISTS_FAILURED";
